server:
  port: 9090
  servlet:
    context-path: /quanly_sach
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quanly_sach
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
jwt:
  secret: 6AqXCh9nL6Wn9bYr5RtxZ+T9H2OsmDhp1XrZwo8Gy30=