server:
  port: 9090
  servlet:
    context-path: /book_management
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_management?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: vthgiang181003@gmail.com
    password: mmwg mjrr xkzi kjhq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Ho_Chi_Minh

  

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
jwt:
  secret: 6AqXCh9nL6Wn9bYr5RtxZ+T9H2OsmDhp1XrZwo8Gy30=

cloudinary:
  cloud-name: duthhwipq
  api-key: 735636338239818
  api-secret: ww3wSfsLqr047sgmPwShAii0iJ8


